# pybricks/robotics/DriveBase.py
class DriveBase:
    def __init__(self, left_motor: Motor, right_motor: Motor, wheel_diameter: int, axle_track: int) -> None: ...
    def drive(self, speed: int, turn_rate: int) -> None: ...
    def drive_time(self, speed: int, turn_rate: int, time: int) -> None: ...
    def drive_distance(self, distance: int, speed: int) -> None: ...
    def drive_angle(self, angle: int, speed: int) -> None: ...
    def stop(self) -> None: ...
    def distance(self) -> int: ...
    def angle(self) -> int: ...
    def reset(self) -> None: ...
    def turn(self, angle: int) -> None: ...