# pybricks/ev3devices/ColorSensor.py
class ColorSensor:
    def __init__(self, port: Any) -> None: ...
    def color(self) -> Any: ...
    def reflection(self) -> int: ...
    def ambient(self) -> int: ...
    def rgb(self) -> Tuple[int, int, int]: ...