# pybricks/ev3devices/GyroSensor.py
class GyroSensor:
    def __init__(self, port: Any, direction: Any = None) -> None: ...
    def angle(self) -> int: ...
    def speed(self) -> int: ...
    def reset_angle(self, angle: int = 0) -> None: 