# pybricks/ev3devices/Motor.py
class Motor:
    def __init__(self, port: Any, positive_direction: Any = None, gears: Any = None) -> None: ...
    def run(self, speed: int) -> None: ...
    def run_time(self, speed: int, time: int, stop_type: Any = None, wait: bool = True) -> None: ...
    def run_angle(self, speed: int, rotation_angle: int, stop_type: Any = None, wait: bool = True) -> None: ...
    def run_target(self, speed: int, target_angle: int, stop_type: Any = None, wait: bool = True) -> None: ...
    def stop(self, stop_type: Any = None) -> None: ...
    def dc(self, duty_cycle: int) -> None: ...
    def hold(self) -> None: ...
    def brake(self) -> None: ...
    def reset_angle(self, angle: int = 0) -> None: ...
    def angle(self) -> int: ...
    def speed(self) -> int: ...
    def stalled(self) -> bool: ...
    def control(self) -> Any: ...