# pybricks/hubs/EV3Brick.py
class EV3Brick:
    def __init__(self) -> None: ...
    def beep(self) -> None: ...
    def speaker(self) -> Any: ...
    def light(self) -> Any: ...
    def display(self) -> Any: ...
    def buttons(self) -> Any: ...
    def play_file(self, file: str) -> None: ...
    def say(self, text: str) -> None: ...
    def stop(self) -> None: ...